@E2E @Regression
# ┌─────────────────────────────────────────────────────────────────────┐
# │  Generated by: AI Feature Generator (Claude API)                    │
# │  Technique:    Boundary Value Analysis (BVA)                        │
# │  Reference:    ISTQB FL 4.2 – Boundary Value Analysis              │
# │                                                                      │
# │  Input: number of children (integer)                                │
# │  Rule:  children count must be between 0 and 10 (inclusive)        │
# │                                                                      │
# │  Boundaries under test:                                             │
# │  ┌────────────────────────────────────────────────────────────┐     │
# │  │  Invalid │ Min │  Valid range   │ Max │ Invalid            │     │
# │  │    -1    │  0  │   1 … 9        │ 10  │  11               │     │
# │  └────────────────────────────────────────────────────────────┘     │
# └─────────────────────────────────────────────────────────────────────┘
Feature: Hotel Search — Boundary Value Analysis on Children Count
  As a QA engineer
  I want to verify the children count field at exact boundary values
  So that the system correctly accepts valid counts and rejects invalid ones

  Background:
    Given I open the Booking.com homepage

  # ── Valid boundaries ───────────────────────────────────────────────────

  @Smoke
  Scenario Outline: Valid children counts at boundaries return search results
    When I search for hotels in "Barcelona" from "2026-07-01" to "2026-07-05" for "2" adults and "<children>" children
    Then I should see search results for "Barcelona" with availability

    Examples: Minimum and maximum valid boundaries
      | children | boundary    |
      | 0        | min (valid) |
      | 1        | min + 1     |
      | 9        | max - 1     |
      | 10       | max (valid) |

  # ── Invalid boundaries ────────────────────────────────────────────────

  @Regression
  Scenario Outline: Children counts outside valid boundaries show a validation error
    When I search for hotels in "Barcelona" from "2026-07-01" to "2026-07-05" for "2" adults and "<children>" children
    Then I should see a validation error message

    Examples: Below minimum and above maximum boundaries
      | children | boundary      |
      | -1       | below min     |
      | 11       | above max     |

  # ── Combined adults + children BVA ───────────────────────────────────

  @Regression
  Scenario Outline: Combined guest count at boundaries
    When I search for hotels in "Rome" from "2026-08-10" to "2026-08-15" for "<adults>" adults and "<children>" children
    Then I should see search results for "Rome" with availability

    Examples: Max adults with boundary children values
      | adults | children | notes              |
      | 30     | 0        | max adults, min ch |
      | 1      | 10       | min adults, max ch |
      | 2      | 5        | typical family     |

  # ── Non-integer input guard ───────────────────────────────────────────

  @Regression
  Scenario: Non-numeric children count is rejected
    When I search for hotels in "Tokyo" from "2026-09-01" to "2026-09-05" for "2" adults and "two" children
    Then I should see a validation error message
