@E2E @Smoke @Regression @WIP
# ┌─────────────────────────────────────────────────────────────────────┐
# │  Generated by: AI Feature Generator (Claude API)                    │
# │  Technique:    Decision Table                                        │
# │  Reference:    ISTQB FL 4.4 – Decision Table Testing                │
# │                                                                      │
# │  Rules under test:                                                   │
# │    R1 – price filter applied  (yes / no)                            │
# │    R2 – currency switched     (yes / no)                            │
# │    Expected outcome varies by combination                           │
# │                                                                      │
# │  Decision table:                                                     │
# │  ┌──────────────────┬─────┬─────┬─────┬─────┐                      │
# │  │ R1 price filter  │  Y  │  Y  │  N  │  N  │                      │
# │  │ R2 currency      │  Y  │  N  │  Y  │  N  │                      │
# │  ├──────────────────┼─────┼─────┼─────┼─────┤                      │
# │  │ filtered+conv.   │  ✓  │     │     │     │                      │
# │  │ filtered only    │     │  ✓  │     │     │                      │
# │  │ converted only   │     │     │  ✓  │     │                      │
# │  │ unfiltered USD   │     │     │     │  ✓  │                      │
# │  └──────────────────┴─────┴─────┴─────┴─────┘                      │
# └─────────────────────────────────────────────────────────────────────┘
Feature: Price Filter with Currency Switch — Decision Table
  As a traveller
  I want to combine price filters with currency selection
  So that I see relevant hotels priced in my preferred currency

  Background:
    Given I open the Booking.com homepage
    And I have searched for hotels in "London" from "2026-08-01" to "2026-08-07"

  # ── Rule combo: price filtered AND currency converted ─────────────────

  @Smoke
  Scenario: Apply price filter and switch currency — results reflect both
    When I apply a price filter from 100 to 300
    And I switch the currency to "EUR"
    Then all displayed prices should be in "EUR"
    And all displayed prices should be between 100 and 300

  # ── Rule combo: price filtered only ───────────────────────────────────

  @Regression
  Scenario: Apply price filter without changing currency — results stay in USD
    When I apply a price filter from 50 to 200
    And I do not change the currency
    Then all displayed prices should be in "USD"
    And all displayed prices should be between 50 and 200

  # ── Rule combo: currency converted only ───────────────────────────────

  @Regression
  Scenario: Switch currency without price filter — all results converted
    When I do not apply a price filter
    And I switch the currency to "GBP"
    Then all displayed prices should be in "GBP"
    And the result count should be the same as without any filter

  # ── Rule combo: no filter, no conversion ──────────────────────────────

  @Regression
  Scenario: No filter and no currency switch — default results in USD
    When I do not apply a price filter
    And I do not change the currency
    Then all displayed prices should be in "USD"
    And the result count should match the total available hotels

  # ── Scenario Outline: price range combinations ─────────────────────────

  @Regression
  Scenario Outline: Price filter with various ranges returns correct subsets
    When I apply a price filter from <min> to <max>
    And I switch the currency to "<currency>"
    Then all displayed prices should be in "<currency>"
    And all displayed prices should be between <min> and <max>

    Examples:
      | min | max | currency |
      | 50  | 150 | USD      |
      | 100 | 250 | EUR      |
      | 200 | 500 | GBP      |

  # ── Edge cases ─────────────────────────────────────────────────────────

  @Regression
  Scenario: Price filter with equal min and max shows no results or exact match
    When I apply a price filter from 180 to 180
    Then I should see either no results or only hotels priced at exactly 180

  @Regression
  Scenario: Price filter with min greater than max shows validation error
    When I apply a price filter from 500 to 100
    Then I should see a validation error message
