@E2E @Regression
# ┌─────────────────────────────────────────────────────────────────────┐
# │  Generated by: AI Feature Generator (Claude API)                    │
# │  Technique:    State Transition                                      │
# │  Reference:    ISTQB FL 4.5 – State Transition Testing              │
# │                                                                      │
# │  States:                                                             │
# │    S1 – Not saved   (hotel not in wishlist)                         │
# │    S2 – Saved       (hotel in wishlist)                             │
# │                                                                      │
# │  Transitions:                                                        │
# │    S1 → S2 : click Save on hotel card       [save]                  │
# │    S2 → S1 : click Remove on hotel card     [remove]                │
# │    S2 → S2 : click Save again (no-op / toggle guard)               │
# │    S1 → S1 : click Remove on unsaved hotel (no-op / guard)         │
# └─────────────────────────────────────────────────────────────────────┘
Feature: Wishlist — State Transition on Save / Remove
  As a logged-in traveller
  I want to save and remove hotels from my wishlist
  So that I can keep track of properties I am considering

  Background:
    Given I open the Booking.com homepage
    And I am logged in as "testuser@example.com" with password "correct_password"
    And I have searched for hotels in "Paris" from "2026-09-01" to "2026-09-05"

  # ── S1 → S2 : save ────────────────────────────────────────────────────

  @Smoke
  Scenario: Save a hotel — transitions from Not Saved to Saved
    Given the first hotel is not in my wishlist
    When I click "Save" on the first hotel
    Then the hotel should appear in my wishlist
    And the Save button should show as active

  # ── S2 → S1 : remove ──────────────────────────────────────────────────

  @Regression
  Scenario: Remove a saved hotel — transitions from Saved to Not Saved
    Given the first hotel is already in my wishlist
    When I click "Remove" on the first hotel
    Then the hotel should no longer appear in my wishlist
    And the Save button should show as inactive

  # ── S1 → S2 → S1 : full round-trip ───────────────────────────────────

  @Regression
  Scenario: Save then remove — full round-trip returns to initial state
    Given the first hotel is not in my wishlist
    When I click "Save" on the first hotel
    Then the hotel should appear in my wishlist
    When I click "Remove" on the first hotel
    Then the hotel should no longer appear in my wishlist

  # ── S2 → S2 : save already-saved (guard) ─────────────────────────────

  @Regression
  Scenario: Clicking Save on an already-saved hotel does not duplicate it
    Given the first hotel is already in my wishlist
    When I click "Save" on the first hotel again
    Then the hotel should appear in my wishlist exactly once

  # ── S1 → S1 : remove unsaved (guard) ─────────────────────────────────

  @Regression
  Scenario: Clicking Remove on an unsaved hotel has no effect
    Given the first hotel is not in my wishlist
    When I click "Remove" on the first hotel
    Then the wishlist should remain empty
    And no error message should be shown

  # ── Multiple hotels ───────────────────────────────────────────────────

  @Regression
  Scenario Outline: Save and remove multiple hotels independently
    Given hotel "<hotel>" is not in my wishlist
    When I click "Save" on "<hotel>"
    Then "<hotel>" should appear in my wishlist
    When I click "Remove" on "<hotel>"
    Then "<hotel>" should no longer appear in my wishlist

    Examples:
      | hotel                 |
      | Hotel Le Marais       |
      | Eiffel Boutique Hotel |
      | Montmartre Garden Inn |
