@API @Regression
# ┌─────────────────────────────────────────────────────────────────────┐
# │  Generated by: AI Feature Generator (Claude API)                    │
# │  Technique:    Equivalence Partitioning (EP)                        │
# │  Reference:    ISTQB FL 4.3 – Equivalence Partitioning             │
# │                                                                      │
# │  Input: review rating (integer)                                     │
# │  Partitions:                                                         │
# │    EP1 – Below valid range  : rating ≤ 0         → 400 Bad Request  │
# │    EP2 – Valid range        : 1 ≤ rating ≤ 5    → 201 Created       │
# │    EP3 – Above valid range  : rating ≥ 6         → 400 Bad Request  │
# │                                                                      │
# │  Input: review comment (string)                                      │
# │  Partitions:                                                         │
# │    EP4 – Empty string       : ""                 → 400 Bad Request  │
# │    EP5 – Valid string       : 1–500 chars        → 201 Created       │
# │    EP6 – Oversized string   : > 500 chars        → 400 Bad Request  │
# └─────────────────────────────────────────────────────────────────────┘
Feature: Hotel Reviews API — Equivalence Partitioning on Rating and Comment
  As a QA engineer
  I want to verify the reviews endpoint handles all input partitions correctly
  So that invalid data is rejected and valid data is accepted

  # ── EP2: valid rating partition ────────────────────────────────────────

  @Smoke
  Scenario Outline: Valid rating values are accepted (EP2)
    When I send POST request to /api/hotel/321/reviews with rating "<rating>" and comment "Great stay!"
    Then the response status code should be 201
    And the response should contain field "id"
    And the response field "rating" should equal "<rating>"

    Examples: Representative values from the valid partition
      | rating |
      | 1      |
      | 3      |
      | 5      |

  # ── EP1: below valid range ────────────────────────────────────────────

  @Regression
  Scenario Outline: Ratings below valid range are rejected (EP1)
    When I send POST request to /api/hotel/321/reviews with rating "<rating>" and comment "Great stay!"
    Then the response status code should be 400
    And the response should contain field "error"

    Examples: Representative values below the valid partition
      | rating |
      | 0      |
      | -1     |
      | -99    |

  # ── EP3: above valid range ────────────────────────────────────────────

  @Regression
  Scenario Outline: Ratings above valid range are rejected (EP3)
    When I send POST request to /api/hotel/321/reviews with rating "<rating>" and comment "Great stay!"
    Then the response status code should be 400
    And the response should contain field "error"

    Examples: Representative values above the valid partition
      | rating |
      | 6      |
      | 10     |
      | 100    |

  # ── EP5: valid comment partition ──────────────────────────────────────

  @Regression
  Scenario Outline: Valid comment lengths are accepted (EP5)
    When I send POST request to /api/hotel/321/reviews with rating "4" and comment "<comment>"
    Then the response status code should be 201
    And the response should contain field "id"

    Examples: Representative values from the valid comment partition
      | comment                                         |
      | OK                                              |
      | Excellent location and very friendly staff.     |
      | The room was spacious and the breakfast was superb. Would recommend to anyone visiting the city for the first time. |

  # ── EP4: empty comment ────────────────────────────────────────────────

  @Regression
  Scenario: Empty comment is rejected (EP4)
    When I send POST request to /api/hotel/321/reviews with rating "4" and comment ""
    Then the response status code should be 400
    And the response should contain field "error"

  # ── EP6: oversized comment ────────────────────────────────────────────

  @Regression
  Scenario: Comment exceeding 500 characters is rejected (EP6)
    When I send POST request to /api/hotel/321/reviews with rating "4" and a comment of 501 characters
    Then the response status code should be 400
    And the response should contain field "error"

  # ── Combined invalid inputs ───────────────────────────────────────────

  @Regression
  Scenario: Both invalid rating and empty comment returns 400
    When I send POST request to /api/hotel/321/reviews with rating "0" and comment ""
    Then the response status code should be 400
    And the response should contain field "error"
