name: Quality Gate - Manual

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Which tests to run?'
        required: true
        default: 'acceptance'
        type: choice
        options:
          - acceptance
          - smoke
          - regression

jobs:
  run-tests:
    name: Run ${{ github.event.inputs.tag }} Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          echo "Installing npm packages (mocked)"
          sleep 2

      - name: Run ${{ github.event.inputs.tag }} tests
        run: |
          echo "Running tests for tag: ${{ github.event.inputs.tag }}"
          echo "::group::Mock Test Output"
          echo "All tests passed ✅"
          echo "::endgroup::"

      - name: Upload Allure report (mock)
        run: |
          mkdir -p allure-results
          echo "Mock Allure Report for ${{ github.event.inputs.tag }}" > allure-results/mock.txt
        continue-on-error: true

      - name: Archive Allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-${{ github.event.inputs.tag }}
          path: allure-results